### ISSUE TITLE
Share Button Social Functionality Issues

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#107]
- If I don't close the social share popup, it persists on other pages. It should close if you leave the page. Example of current issue:

https://github.com/ucd-library/dams/assets/17831969/3e7f1d9a-7b40-43dd-9b23-b8d1ee3020ca

- When on the page, it isn't super intuitive to close the button since you have to click the button itself to do it. A click anywhere outside of the overlay would be better. 

- The Pinterest button doesn't work. Nothing happens when it is clicked. 

- When you share an item to Twitter it says "undefined" as the title of the link. Can we set it to pull the item title for this any other social that allows us to define it?

- Twitter rebranded, so we need to change the Twitter icon out for the new X Logo. icon: https://fontawesome.com/icons/x-twitter?f=brands&s=solid 

![image](https://github.com/ucd-library/dams/assets/17831969/3a32df77-b266-47a4-bf68-4994b2608e41)

As long as they are still using "twitter.com" as primary URL I feel we should maintain Twitter in the name. When it fully shifts over, we can drop it from the label.

**Comment by UcDust** [comment]
@wrenaria 

I'll create a PR into sandbox for this. I can't test Pinterest completely because when trying to add it to the board it seems to fail, I think because the url is pointing at my local machine. We'll have to finish testing once it's deployed to sandbox. But at least the errors it was throwing previously are addressed, as well as the other items.
